"""Agrega campos de portal a aliados

Revision ID: 035ccac18a82
Revises: ef6eb2d7155d
Create Date: 2026-08-18 15:01:58.529072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035ccac18a82'
down_revision: Union[str, Sequence[str], None] = 'ef6eb2d7155d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliados_comerciales', sa.Column('qr_access_token', sa.String(), nullable=True))
    op.add_column('aliados_comerciales', sa.Column('correo_contacto', sa.String(), nullable=True))
    op.add_column('aliados_comerciales', sa.Column('telefono_contacto', sa.String(), nullable=True))
    op.add_column('aliados_comerciales', sa.Column('logo_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_aliados_comerciales_qr_access_token'), 'aliados_comerciales', ['qr_access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aliados_comerciales_qr_access_token'), table_name='aliados_comerciales')
    op.drop_column('aliados_comerciales', 'logo_url')
    op.drop_column('aliados_comerciales', 'telefono_contacto')
    op.drop_column('aliados_comerciales', 'correo_contacto')
    op.drop_column('aliados_comerciales', 'qr_access_token')
    # ### end Alembic commands ###
