"""Agrega seccion a catalogo

Revision ID: 2e7d0fdff394
Revises: ce7ee6c2f47e
Create Date: 2026-08-19 14:37:20.508571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7d0fdff394'
down_revision: Union[str, Sequence[str], None] = 'ce7ee6c2f47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_items', sa.Column('seccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogo_items', 'seccion')
    # ### end Alembic commands ###
