"""Agrega coordenadas a aliados

Revision ID: 412f9de20bcd
Revises: 035ccac18a82
Create Date: 2026-08-18 15:19:46.103802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412f9de20bcd'
down_revision: Union[str, Sequence[str], None] = '035ccac18a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliados_comerciales', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('aliados_comerciales', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('aliados_comerciales', sa.Column('longitud', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliados_comerciales', 'longitud')
    op.drop_column('aliados_comerciales', 'latitud')
    op.drop_column('aliados_comerciales', 'direccion')
    # ### end Alembic commands ###
