"""Agrega columnas de contacto airbnb

Revision ID: 683b9d547705
Revises: 6e5ae32d2326
Create Date: 2026-08-14 15:49:33.736855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683b9d547705'
down_revision: Union[str, Sequence[str], None] = '6e5ae32d2326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades_airbnb', sa.Column('airbnb_nombre', sa.String(), nullable=True))
    op.add_column('propiedades_airbnb', sa.Column('airbnb_telefono', sa.String(), nullable=True))
    op.add_column('propiedades_airbnb', sa.Column('airbnb_correo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades_airbnb', 'airbnb_correo')
    op.drop_column('propiedades_airbnb', 'airbnb_telefono')
    op.drop_column('propiedades_airbnb', 'airbnb_nombre')
    # ### end Alembic commands ###
