"""Esquema completo con catalogo, pedidos y pagos

Revision ID: 6e5ae32d2326
Revises: a87cec235899
Create Date: 2026-08-11 10:52:33.272173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5ae32d2326'
down_revision: Union[str, Sequence[str], None] = 'a87cec235899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aliado_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio_base', sa.Float(), nullable=False),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('orden_display', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aliado_id'], ['aliados_comerciales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_items_id'), 'catalogo_items', ['id'], unique=False)
    op.create_table('pedidos_transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propiedad_id', sa.Integer(), nullable=True),
    sa.Column('aliado_id', sa.Integer(), nullable=True),
    sa.Column('huesped_nombre', sa.String(), nullable=True),
    sa.Column('huesped_contacto', sa.String(), nullable=True),
    sa.Column('estado_operativo', sa.String(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aliado_id'], ['aliados_comerciales.id'], ),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedades_airbnb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_transaccion_id'), 'pedidos_transaccion', ['id'], unique=False)
    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('notas_personalizadas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['catalogo_items.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_transaccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_pedido_id'), 'detalles_pedido', ['id'], unique=False)
    op.create_table('liquidaciones_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('gateway_tx_id', sa.String(), nullable=True),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('monto_bruto', sa.Float(), nullable=False),
    sa.Column('comision_plataforma', sa.Float(), nullable=False),
    sa.Column('monto_aliado', sa.Float(), nullable=False),
    sa.Column('estado_pago', sa.String(), nullable=True),
    sa.Column('desembolsado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_transaccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_tx_id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_liquidaciones_pago_id'), 'liquidaciones_pago', ['id'], unique=False)
    op.add_column('propiedades_airbnb', sa.Column('direccion_apto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades_airbnb', 'direccion_apto')
    op.drop_index(op.f('ix_liquidaciones_pago_id'), table_name='liquidaciones_pago')
    op.drop_table('liquidaciones_pago')
    op.drop_index(op.f('ix_detalles_pedido_id'), table_name='detalles_pedido')
    op.drop_table('detalles_pedido')
    op.drop_index(op.f('ix_pedidos_transaccion_id'), table_name='pedidos_transaccion')
    op.drop_table('pedidos_transaccion')
    op.drop_index(op.f('ix_catalogo_items_id'), table_name='catalogo_items')
    op.drop_table('catalogo_items')
    # ### end Alembic commands ###
