"""Agrega columna imagen_url

Revision ID: a0848cd1ae5a
Revises: 683b9d547705
Create Date: 2026-08-18 10:28:55.381307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0848cd1ae5a'
down_revision: Union[str, Sequence[str], None] = '683b9d547705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades_airbnb', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades_airbnb', 'imagen_url')
    # ### end Alembic commands ###
