"""Creacion inicial tablas

Revision ID: a87cec235899
Revises: 
Create Date: 2026-08-03 16:04:44.458794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87cec235899'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('requiere_despacho', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_servicio_id'), 'categorias_servicio', ['id'], unique=False)
    op.create_table('zonas_geograficas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonas_geograficas_id'), 'zonas_geograficas', ['id'], unique=False)
    op.create_index(op.f('ix_zonas_geograficas_nombre'), 'zonas_geograficas', ['nombre'], unique=True)
    op.create_table('aliados_comerciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('estado_operativo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_servicio.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas_geograficas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliados_comerciales_id'), 'aliados_comerciales', ['id'], unique=False)
    op.create_table('propiedades_airbnb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('qr_access_token', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas_geograficas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propiedades_airbnb_id'), 'propiedades_airbnb', ['id'], unique=False)
    op.create_index(op.f('ix_propiedades_airbnb_qr_access_token'), 'propiedades_airbnb', ['qr_access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propiedades_airbnb_qr_access_token'), table_name='propiedades_airbnb')
    op.drop_index(op.f('ix_propiedades_airbnb_id'), table_name='propiedades_airbnb')
    op.drop_table('propiedades_airbnb')
    op.drop_index(op.f('ix_aliados_comerciales_id'), table_name='aliados_comerciales')
    op.drop_table('aliados_comerciales')
    op.drop_index(op.f('ix_zonas_geograficas_nombre'), table_name='zonas_geograficas')
    op.drop_index(op.f('ix_zonas_geograficas_id'), table_name='zonas_geograficas')
    op.drop_table('zonas_geograficas')
    op.drop_index(op.f('ix_categorias_servicio_id'), table_name='categorias_servicio')
    op.drop_table('categorias_servicio')
    # ### end Alembic commands ###
