"""Agrega nombre de contacto a aliados

Revision ID: ce7ee6c2f47e
Revises: 412f9de20bcd
Create Date: 2026-08-18 17:53:26.233112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7ee6c2f47e'
down_revision: Union[str, Sequence[str], None] = '412f9de20bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliados_comerciales', sa.Column('nombre_contacto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliados_comerciales', 'nombre_contacto')
    # ### end Alembic commands ###
