"""Agrega descripcion, icono y activo a categorias

Revision ID: ef6eb2d7155d
Revises: a0848cd1ae5a
Create Date: 2026-08-18 12:32:49.916766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6eb2d7155d'
down_revision: Union[str, Sequence[str], None] = 'a0848cd1ae5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias_servicio', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('categorias_servicio', sa.Column('icono', sa.String(), nullable=True))
    op.add_column('categorias_servicio', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias_servicio', 'activo')
    op.drop_column('categorias_servicio', 'icono')
    op.drop_column('categorias_servicio', 'descripcion')
    # ### end Alembic commands ###
